spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

questionsservice.getids.uri=http://QUESTIONSSERVICE/questions/getQuestionIds/
questionsservice.getquestions.uri=http://QUESTIONSSERVICE/questions/getQuestionsWithIds
